### ISSUE TITLE
Create research translations as blog entries. 

### ISSUE THREAD

**Issue by jkuruzovich** [SeverinoCenter/ecosystemdata#6]
Research translation 1.docx
Research translation 2.docx

The goal is to make these look like medium style articles, with relevant CC0 images perhaps. You can just do them as a blog post.

**Comment by jkuruzovich** [comment]
[Research translation 2.docx](https://github.com/SeverinoCenter/ecosystemdata/files/7998396/Research.translation.2.docx)
[Research translation 1.docx](https://github.com/SeverinoCenter/ecosystemdata/files/7998397/Research.translation.1.docx)

**Comment by jkuruzovich** [comment]
Should be attributed to Xinying Qu  and Jason Kuruzovich in that order.

**Comment by norbusonam** [comment]
@jkuruzovich made some progress on this. I pushed so it should be accessible here: 

https://startupcommunities.org/blog/

Let me know what you think
